## Arrays reorganizing

### `arange()`

The **`arange()`** is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval. For instance, you want to create values from 1 to 10; you can use **`arange()`** function.

**Syntax:**
```python
numpy.arange(start, stop,step) 
```
* **`start`**: Start of interval
* **`stop`**: End of interval
* **`step`**: Spacing between values. Default step is 1

In [2]:
# Example 1:

import numpy as np
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If you want to change the step, you can add a third number in the parenthesis. It will change the step.

In [5]:
# Example 2:

import numpy as np
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [6]:
np.arange(0,11,2)   # even no by adding a step size

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.arange(1,11,2)   # odd no

array([1, 3, 5, 7, 9])

### Reshape Data

In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. 

**Syntax:** 
```python
numpy.reshape(a, newShape, order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [1]:
import numpy as np

e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

### Broadcasting with array reorganizing 

It's super cool and super useful. The one-line explanation is that when doing elementwise operations, things expand to the "correct" shape.

In [2]:
# add a scalar to a 1-d array
x = np.arange(5)
print('x:  ', x)
print('x+1:', x + 1, end='\n\n')

y = np.random.uniform(size=(2, 5))
print('y:  ', y,  sep='\n')
print('y+1:', y + 1, sep='\n')

x:   [0 1 2 3 4]
x+1: [1 2 3 4 5]

y:  
[[0.32868583 0.63129471 0.00445107 0.70757464 0.10198788]
 [0.87702771 0.23507173 0.1115813  0.50613393 0.36622745]]
y+1:
[[1.32868583 1.63129471 1.00445107 1.70757464 1.10198788]
 [1.87702771 1.23507173 1.1115813  1.50613393 1.36622745]]


Since `x` is shaped `(5,)` and `y` is shaped `(2,5)` we can do operations between them.

In [3]:
x * y

array([[0.        , 0.63129471, 0.00890214, 2.12272392, 0.40795152],
       [0.        , 0.23507173, 0.2231626 , 1.51840179, 1.46490979]])

Without broadcasting we'd have to manually reshape our arrays, which quickly gets annoying.

In [4]:
x.reshape(1, -1).repeat(2, axis=0) * y

array([[0.        , 0.63129471, 0.00890214, 2.12272392, 0.40795152],
       [0.        , 0.23507173, 0.2231626 , 1.51840179, 1.46490979]])

In [7]:
print(x.reshape(1, -1).repeat(2, axis=0))

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [6]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Flatten Data

When you deal with some neural network like convnet, you need to flatten the array. You can use **`flatten()`**.

**Syntax:** 
```python
numpy.flatten(order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [8]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

### What is `hstack`?

With **`hstack`** you can appened data horizontally. This is a very convinient function in Numpy. Lets study it with an example:

In [14]:
## Horitzontal Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [15]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### What is `vstack`?

With **`vstack`** you can appened data vertically. Lets study it with an example:

In [9]:
## Vertical Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append: \n', np.vstack((f, g)))

Vertical Append: 
 [[1 2 3]
 [4 5 6]]


In [17]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Generate Random Numbers

To generate random numbers for Gaussian distribution use:

**Syntax:**
```python
numpy.random.normal(loc, scale, size)
```
* **`loc`**: the mean. The center of distribution
* **`scale`**: standard deviation.
* **`size`**: number of returns

In [10]:
## Generate random number from normal distribution

normal_array = np.random.normal(5, 0.5, (10,2))
print(normal_array)

[[4.30802362 4.88087118]
 [5.39995972 4.4251042 ]
 [5.02526007 5.03731235]
 [4.89090515 4.32137995]
 [5.21493089 5.15613492]
 [5.04357467 5.20420125]
 [5.65002749 4.83717443]
 [5.30272026 5.26349679]
 [5.84715053 4.61273483]
 [5.29609019 4.97293191]]


### Linspace

Linspace gives evenly spaced samples.

**Syntax:**
```python
numpy.linspace(start, stop, num, endpoint)
```
* **`start`**: Start of sequence
* **`stop`**: End of sequence
* **`num`**: Number of samples to generate. Default is 50
* **`endpoint`**: If **`True`** (default), stop is the last value. If **`False`**, stop value is not included.

In [12]:
# Example:

import numpy as np
np.linspace(0,10,6) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [2]:
# Example: For instance, it can be used to create 10 values from 1 to 5 evenly spaced.

import numpy as np
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

If you do not want to include the last digit in the interval, you can set endpoint to **`False`**

In [4]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

### LogSpace

LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as **`np.linspace`**.

**Syntax:**
```python
numpy.logspace(start, stop, num, endpoint)
```
* **`start`**: Start of sequence
* **`stop`**: End of sequence
* **`num`**: Number of samples to generate. Default is 50
* **`endpoint`**: If **`True`** (default), stop is the last value. If **`False`**, stop value is not included.

In [22]:
# Example:

np.logspace(3.0, 4.0, num=4)#10**(np.linspace(3.,4.,num=4))

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [13]:
10**(np.linspace(3.,4.,num=4))

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

Finaly, if you want to check the memory size of an element in an array, you can use **`.itemsize`**

In [14]:
x = np.array([1,2,3], dtype=np.float32)
x.itemsize

4

## Statistics

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array. The functions are explained as follows −

Numpy is equipped with the robust statistical function as listed below:

| Function | Numpy |
|:----: |:---- |
| **`Min`**                | **np.min()** | 
| **`Max`**                | **np.max()** | 
| **`Mean`**               | **np.mean()** | 
| **`Median`**             | **np.median()** | 
| **`Standard deviation`** | **np.std()** | 

In [15]:
# Consider the following Array

import numpy as np

normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.051311   4.60512499 5.10237689 5.98122375 4.216026   4.80739818
 5.00386019 5.04876161 5.33614096 4.72875345]


In [16]:
# Example:Statistical function

### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.216025997680019
5.981223748202368
4.988097700971334
5.026310904072112
0.44396984617595064


In [26]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.min(stats)

1

In [28]:
np.max(stats, axis=1)

array([3, 6])

In [29]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Load Data from File

you can download the "data.txt" from **[here](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/data.txt)**

In [19]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') # you can also change type to 'int64'
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
